apiVersion: v1
kind: Secret
metadata:
  name: memberlist
  namespace: metallb-system
stringData:
  secretkey: "4jy5OeW9RNUc95g+Ij3cMGZFkoLqn3tiV3QaUe4CZBo8cJR73fpc3lw5PSjnh40p\n10N8naG89rzWD1/JX0eHnscL5T5PNRZERAdlJYTKwjB6jJg8ygN6sgLSKPsPDonC\nqXaxdyLUHm8NxWGlJTzevq6Bntc6uKERSqujjTs+gNs="
